apiVersion: apps/v1
kind: Deployment
 
metadata:
  name: spring-crud-app
 
spec:
  replicas: 2
 
  selector:
    matchLabels:
      app: spring-crud-app
 
  template:
    metadata:
      labels:
        app: spring-crud-app
 
    spec:
      containers:
      - name: spring-crud-app
 
        image: narasimhamadesh/spring-crud-app:latest
 
        ports:
        - containerPort: 8080
